/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ipt.poo.proj.app;

import javax.swing.JOptionPane;

/**
 * GUI para vermos o Tetris em tempo real
 * @author bento
 * Imagem do background: https://www.itl.cat/wallview/iiobTxb_tetris-matrix-iphone-5-wallpaper-tetris-matrix/
 * 
 */
public class Tetris extends javax.swing.JFrame {
    /**
     * Creates new form Tetris
     */
    public Tetris() {
        initComponents();
        setLocationRelativeTo(null);
        tabuleiro1.getTimer().start();
        tabuleiro1.requestFocus();
        tabuleiro1.setLabelScore(scoreText);
        tabuleiro1.setLabelLinhas(linhasText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Container = new javax.swing.JPanel();
        linhasText = new javax.swing.JLabel();
        linhasLabel = new javax.swing.JLabel();
        scoreText = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        SairButton = new javax.swing.JButton();
        Controlos = new javax.swing.JButton();
        RegrasButton = new javax.swing.JButton();
        PauseButton = new javax.swing.JButton();
        RecomecarButton = new javax.swing.JButton();
        NovoJogoButton = new javax.swing.JButton();
        tabuleiro1 = new edu.ipt.poo.proj.libs.Tabuleiro();
        Img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("T | E | T | R | I | S |");
        setBackground(new java.awt.Color(255, 51, 51));
        setPreferredSize(new java.awt.Dimension(540, 397));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Container.setLayout(null);

        linhasText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        linhasText.setForeground(new java.awt.Color(102, 255, 0));
        linhasText.setText("0");
        Container.add(linhasText);
        linhasText.setBounds(450, 80, 90, 30);

        linhasLabel.setFont(new java.awt.Font("Agency FB", 0, 26)); // NOI18N
        linhasLabel.setForeground(new java.awt.Color(102, 255, 102));
        linhasLabel.setText("Linhas");
        Container.add(linhasLabel);
        linhasLabel.setBounds(380, 60, 90, 80);

        scoreText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        scoreText.setForeground(new java.awt.Color(102, 255, 0));
        scoreText.setText("0");
        Container.add(scoreText);
        scoreText.setBounds(450, 30, 130, 40);

        scoreLabel.setFont(new java.awt.Font("Agency FB", 0, 26)); // NOI18N
        scoreLabel.setForeground(new java.awt.Color(102, 255, 102));
        scoreLabel.setText("Score");
        Container.add(scoreLabel);
        scoreLabel.setBounds(380, 20, 70, 60);

        SairButton.setBackground(new java.awt.Color(0, 0, 0));
        SairButton.setForeground(new java.awt.Color(102, 255, 0));
        SairButton.setText("Sair");
        SairButton.setBorderPainted(false);
        SairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairButtonActionPerformed(evt);
            }
        });
        Container.add(SairButton);
        SairButton.setBounds(400, 240, 90, 24);

        Controlos.setBackground(new java.awt.Color(0, 0, 0));
        Controlos.setForeground(new java.awt.Color(102, 255, 0));
        Controlos.setText("Controlos");
        Controlos.setBorderPainted(false);
        Controlos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ControlosActionPerformed(evt);
            }
        });
        Container.add(Controlos);
        Controlos.setBounds(400, 190, 90, 24);

        RegrasButton.setBackground(new java.awt.Color(0, 0, 0));
        RegrasButton.setForeground(new java.awt.Color(102, 255, 0));
        RegrasButton.setText("Regras");
        RegrasButton.setBorderPainted(false);
        RegrasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegrasButtonActionPerformed(evt);
            }
        });
        Container.add(RegrasButton);
        RegrasButton.setBounds(400, 150, 90, 24);

        PauseButton.setBackground(new java.awt.Color(0, 0, 0));
        PauseButton.setForeground(new java.awt.Color(102, 255, 0));
        PauseButton.setText("Pausar");
        PauseButton.setBorderPainted(false);
        PauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PauseButtonActionPerformed(evt);
            }
        });
        Container.add(PauseButton);
        PauseButton.setBounds(50, 30, 100, 24);

        RecomecarButton.setBackground(new java.awt.Color(0, 0, 0));
        RecomecarButton.setForeground(new java.awt.Color(102, 255, 0));
        RecomecarButton.setText("Recomeçar");
        RecomecarButton.setBorderPainted(false);
        RecomecarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecomecarButtonActionPerformed(evt);
            }
        });
        Container.add(RecomecarButton);
        RecomecarButton.setBounds(50, 60, 100, 24);

        NovoJogoButton.setBackground(new java.awt.Color(0, 0, 0));
        NovoJogoButton.setForeground(new java.awt.Color(102, 255, 0));
        NovoJogoButton.setText("Novo Jogo");
        NovoJogoButton.setBorderPainted(false);
        NovoJogoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoJogoButtonActionPerformed(evt);
            }
        });
        Container.add(NovoJogoButton);
        NovoJogoButton.setBounds(50, 90, 100, 24);
        Container.add(tabuleiro1);
        tabuleiro1.setBounds(170, 10, 180, 310);

        Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/background_tetris_matrix.jpg"))); // NOI18N
        Img.setText(" ");
        Container.add(Img);
        Img.setBounds(0, 0, 540, 360);

        getContentPane().add(Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PauseButtonActionPerformed
        // TODO add your handling code here:
        tabuleiro1.Pause();
    }//GEN-LAST:event_PauseButtonActionPerformed

    private void NovoJogoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoJogoButtonActionPerformed
        // TODO add your handling code here:
        tabuleiro1.NovoJogo();
    }//GEN-LAST:event_NovoJogoButtonActionPerformed

    private void RecomecarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecomecarButtonActionPerformed
        // TODO add your handling code here:
        tabuleiro1.Start();
    }//GEN-LAST:event_RecomecarButtonActionPerformed

    private void RegrasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegrasButtonActionPerformed
        // TODO add your handling code here:
        tabuleiro1.Pause();
        JOptionPane.showMessageDialog(this, "O jogo é composto por 7 peças (com forma de I, J, L, O, S, T e Z). "
                + "\n" + "As peças caem aleatóriamente. "
                + "\n" + "O jogador deve controlar as peças e fazer com que elas se encaixem com as que já estão no tabuleiro. "
                + "\n" + "Quando conseguir preencher totalmente uma linha horizontal, a linha desaparecerá.", "Regras", 1);
        tabuleiro1.Start();
    }//GEN-LAST:event_RegrasButtonActionPerformed

    private void ControlosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ControlosActionPerformed
        // TODO add your handling code here:
        tabuleiro1.Pause();
        JOptionPane.showMessageDialog(this, "Para mover as peças para o lado esquerdo e direito usar as teclas das setas da esquerda e direita, respetivamente."
                + "\n" + "Para mover a peça rapidamente para baixo usar a tecla da seta para baixo."
                + "\n" + "Para mover a peça imediatamente para baixo usar a tecla da seta para cima."
                + "\n" + "Para rodar as peça na direção horário usar o botão direito do rato."
                + "\n" + "Para rodar as peça na direção anti-horário usar o botão esquerdo do rato.", "Controlos", 1);
        tabuleiro1.Start();
    }//GEN-LAST:event_ControlosActionPerformed

    private void SairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SairButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tetris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tetris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tetris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tetris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tetris().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JButton Controlos;
    private javax.swing.JLabel Img;
    private javax.swing.JButton NovoJogoButton;
    private javax.swing.JButton PauseButton;
    private javax.swing.JButton RecomecarButton;
    private javax.swing.JButton RegrasButton;
    private javax.swing.JButton SairButton;
    private javax.swing.JLabel linhasLabel;
    private javax.swing.JLabel linhasText;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel scoreText;
    private edu.ipt.poo.proj.libs.Tabuleiro tabuleiro1;
    // End of variables declaration//GEN-END:variables
}
